apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-gwv6-fetch-secret
data:
  custom-gwv6-fetch-secret.sh: |+
    #!/bin/sh
    export TMPDIR=/tmp/secret
    export LIST_CM=gwcfg-list
    export NS=default
    export OUTDIR=/tmp/secret
    readiness() {
      curl http://127.0.0.1:2999/ready
    }
    curl_to_master() {
      curl -s -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
              -H 'Accept: application/json' \
              --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
              --url "$1"
    }
    [ ! -d ${TMPDIR} ] && mkdir -p ${TMPDIR}
    [ ! -d ${OUTDIR} ] && mkdir -p ${OUTDIR}
    # fetch ConfigMap conatains the Secrets list to fetch
    [ ! -z ${LIST_CM} ] && \
    curl_to_master https://kubernetes.default.svc.cluster.local/api/v1/namespaces/${NS}/configmaps/${LIST_CM} \
      | awk 'BEGIN{flg=1}{if($0~/"data":\s*[{]/){ flg=0;next}; if($0~/^\s+[}]/){flg=1}; if(flg==0){ gsub("[\":]","",$1); first=$1; $1=""; off=match($0,"\"")+1; body=substr($0,off,match($0,"\"[, ]*$")-off); print body } }' \
      | sed -e 's/\([^\]\)\\n/\1\'$'\n''/g' -e 's/\\"/"/g' \
      | sed 's/^\\n/\'$'\n''/' \
    | while read SECRET;do
        [ ${#SECRET} -gt 0 ] && \
        curl_to_master https://kubernetes.default.svc.cluster.local/api/v1/namespaces/${NS}/secrets/${SECRET} \
         | awk 'BEGIN{flg=1}{if($0~/"data":\s*[{]/){flg=0;next};if($0~/^\s+[}]/){flg=1};if(flg==0){gsub("[\":]","",$1);first=$1;$1="";off=match($0,"\"")+1;body=substr($0,off,match($0,"\"[, ]*$")-off); print body> "'${TMPDIR}'/"first}}'
      done
    for f in $(ls ${TMPDIR}/*);do
      base64 -d $f > ${OUTDIR}/$(basename $f)
    done
    readiness

